import type { Job } from './types';
const MOCK_JOBS_DATA: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'Vercel',
    location: 'Remote',
    tags: ['React', 'TypeScript', 'Next.js'],
    url: 'https://vercel.com/careers',
    postedDate: new Date('2024-05-20T10:00:00Z').toISOString(),
    description: 'Join Vercel to build the future of the web. We are looking for a senior frontend engineer with a passion for performance and user experience.',
    skills: ['React', 'TypeScript', 'Next.js', 'Node.js', 'Performance Optimization'],
    jobType: 'Full-time',
  },
  {
    id: '2',
    title: 'Full-Stack Developer',
    company: 'Cloudflare',
    location: 'San Francisco, CA',
    tags: ['Go', 'React', 'Workers'],
    url: 'https://www.cloudflare.com/careers/',
    postedDate: new Date('2024-05-19T14:30:00Z').toISOString(),
    description: 'Work on mission-critical infrastructure at Cloudflare. We are hiring full-stack developers to build and maintain our global network.',
    skills: ['Go', 'React', 'TypeScript', 'Kubernetes', 'Docker'],
    jobType: 'Full-time',
  },
  {
    id: '3',
    title: 'Backend Engineer (Rust)',
    company: 'Fly.io',
    location: 'Remote',
    tags: ['Rust', 'PostgreSQL', 'GraphQL'],
    url: 'https://fly.io/jobs/',
    postedDate: new Date('2024-05-21T09:00:00Z').toISOString(),
    description: 'Build high-performance backend services in Rust. Experience with distributed systems and cloud infrastructure is a plus.',
    skills: ['Rust', 'PostgreSQL', 'GraphQL', 'Distributed Systems', 'Linux'],
    jobType: 'Full-time',
  },
  {
    id: '4',
    title: 'DevOps Engineer',
    company: 'GitHub',
    location: 'Remote',
    tags: ['Kubernetes', 'Terraform', 'AWS'],
    url: 'https://github.com/careers',
    postedDate: new Date('2024-05-18T12:00:00Z').toISOString(),
    description: 'Help maintain and scale GitHub\'s infrastructure. We are looking for a DevOps engineer with experience in CI/CD and cloud automation.',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Azure'],
    jobType: 'Contract',
  },
  {
    id: '5',
    title: 'UI/UX Designer',
    company: 'Linear',
    location: 'Remote',
    tags: ['Figma', 'UI', 'UX'],
    url: 'https://linear.app/careers',
    postedDate: new Date('2024-05-21T11:00:00Z').toISOString(),
    description: 'Design beautiful and intuitive interfaces for Linear. We are looking for a talented UI/UX designer to join our remote team.',
    skills: ['Figma', 'UI Design', 'UX Research', 'Prototyping'],
    jobType: 'Full-time',
  },
  {
    id: '6',
    title: 'Product Manager',
    company: 'Stripe',
    location: 'Dublin, Ireland',
    tags: ['Product', 'FinTech', 'API'],
    url: 'https://stripe.com/jobs',
    postedDate: new Date('2024-05-20T16:00:00Z').toISOString(),
    description: 'Lead the development of new products at Stripe. We are looking for an experienced product manager to drive our API-first strategy.',
    skills: ['Product Management', 'Agile', 'API Design', 'FinTech'],
    jobType: 'Full-time',
  },
  {
    id: '7',
    title: 'Software Engineering Intern',
    company: 'Google',
    location: 'Bangalore, India',
    tags: ['Internship', 'C++', 'Java'],
    url: 'https://careers.google.com/',
    postedDate: new Date('2024-05-22T10:00:00Z').toISOString(),
    description: 'Join Google as a software engineering intern and work on challenging projects with a global impact.',
    skills: ['C++', 'Java', 'Python', 'Data Structures', 'Algorithms'],
    jobType: 'Internship',
  },
];
export const MOCK_JOBS = MOCK_JOBS_DATA;